#!/usr/bin/env python3
from ocflib.misc.shell import *


def bg_none(string):
    return string

def none(string):
    return string


if __name__ == '__main__':
    for bg_color in COLORS + ['none']:
        for fg_color in COLORS:
            # this is horrible
            fg_func = locals()[fg_color]
            bg_func = locals()['bg_' + bg_color]

            print(fg_func(bg_func("This is {fg} text with a {bg} background".format(fg=fg_color, bg=bg_color))))
