#!/usr/bin/env python3
import getpass

import ocflib.account.manage

if __name__ == '__main__':
    ocflib.account.manage.change_password_with_staffer(
        input('Account: '),
        getpass.getpass('New password: '),
        'ckuehl/admin',
        getpass.getpass('Admin password: '))
