#!/usr/bin/env python3
import getpass

import ocflib.account.manage

if __name__ == "__main__":
    ocflib.account.manage.change_password_with_keytab(
        input("Account: "),
        getpass.getpass("New password: "),
        "/home/c/ck/ckuehl/chpass.keytab",
        "chpass/earthquake.ocf.berkeley.edu",
    )
