#!/usr/bin/env python3
import getpass

import ocflib.account.utils

if __name__ == "__main__":
    matches = ocflib.account.utils.password_matches(
        input("Account: "), getpass.getpass("Password: "),
    )
    print("Matches: {}".format(matches))
