#!/usr/bin/env python3
import time

from celery import Celery
from celery.exceptions import TimeoutError
from ocflib.account.submission import get_tasks


if __name__ == '__main__':
    url = 'redis://create.ocf.berkeley.edu:6379'
    celery_app = Celery(broker=url, backend=url)
    tasks = get_tasks(celery_app)

    result = tasks.create_account.delay(3)
    print("Resolving immediately...")
    try:
        print(result.wait(timeout=5))
    except TimeoutError as ex:
        print("Didn't resolved within timeout:")
        print(ex)

    print("Waiting to resolve...")
    result = tasks.create_account.delay(3)
    while not result.ready():
        print("waiting... (task id: " + result.id + ")")
        time.sleep(1)
    print(result.result)
