#!/usr/bin/env python3
import ocflib.calnet.directory as directory

if __name__ == '__main__':
    print("Names for user 1034192:\n{}".format(
        directory.get_calnet_names('1034192')))

    print("Name for user 1034192:\n{}".format(
        directory.name_by_calnet_uid('1034192')))
