#!/usr/bin/env python3
import ocflib.calnet.utils as utils

if __name__ == '__main__':
    print("Names for user 1034192:\n{}".format(
        utils.get_calnet_names('1034192')))

    print("Name for user 1034192:\n{}".format(
        utils.name_by_calnet_uid('1034192')))
