#!/usr/bin/env python3
from getpass import getpass

from ocflib.infra.rt import rt_connection
from ocflib.infra.rt import RtTicket


if __name__ == "__main__":
    rt = rt_connection(user=input("username: "), password=getpass())
    print(RtTicket.from_number(rt, 4589))
