name: Publish

on:
  workflow_dispatch:
  push:
    branches: [master]

defaults:
  run:
    shell: bash

jobs:
  deploy:
    if: github.repository == 'ocf/ocflib'
    name: Publish
    runs-on: ci-ocf-ocflib
    permissions:
      id-token: write
    steps:
      - name: Checkout branch
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
      - name: Nix develop
        uses: nicknovitski/nix-develop@9be7cfb4b10451d3390a75dc18ad0465bed4932a
      - name: Install dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install
      - name: Run tests
        run: |
          poetry run pytest
      - name: Build package 
        run: |
          poetry build
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33
