name: Publish

on:
  workflow_dispatch:
  push:
    branches: [master]

defaults:
  run:
    shell: bash

jobs:
  deploy:
    if: github.repository == 'ocf/ocflib'
    name: Publish
    runs-on: ci-ocf-ocflib
    steps:
      - name: Checkout branch
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          nix develop -c poetry config virtualenvs.in-project true
          nix develop -c poetry install
      - name: Run tests
        run: |
          nix develop -c poetry run pytest
      - name: Build package 
        run: |
          nix develop -c poetry build
      - name: Publish to PyPi
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          nix develop -c poetry publish --username __token__ --password $PYPI_TOKEN
